### ISSUE TITLE
Rebuild image

### ISSUE THREAD

**Issue by NickHu** [h0tbird/docker-portus#12]
Could we please get a rebuild of this image pushed to Docker hub?

There have been some additions and fixes upstream that I think are pretty useful.

See:
* https://github.com/SUSE/Portus/pull/1054
* https://github.com/SUSE/Portus/pull/1017
* https://github.com/SUSE/Portus/pull/1031

Perhaps a new image should be build whenever there is a commit upstream?

**Comment by h0tbird** [comment]
I will manually trigger a rebuild but I don't know how to automate this based on upstream changes. Any idea?

**Comment by h0tbird** [comment]
Done. https://hub.docker.com/r/h0tbird/portus/builds/bkyv6hmnhxqkvonozjckqqd/

**Comment by h0tbird** [comment]
I have also linked the `h0tbird/portus` automated build to `opensuse/portus`. But the upstream repository is https://github.com/openSUSE/docker-containers and not https://github.com/SUSE/Portus

**Comment by h0tbird** [comment]
Too bad the `opensuse/portus` linked repository is not triggering builds of `h0tbird/portus`.
I don't know why :( but this is all I can do right now.
