### ISSUE TITLE
Why not the official registry image?

### ISSUE THREAD

**Issue by oblique** [h0tbird/docker-portus#13]
I there any technical reason why you choose to create your own [registry](https://github.com/h0tbird/docker-registry) image?

**Comment by h0tbird** [comment]
I did it because I wanted to replace the entrypoint in order to run my own initialisation script which takes care of importing trusted SSL certificates at runtime: https://github.com/h0tbird/docker-registry/blob/8b0d8289d582cf5132ce1432963e4a6742adc218/rootfs/init#L7-L35

**Comment by oblique** [comment]
Cool thanks!
