### ISSUE TITLE
Simplify image configuration

### ISSUE THREAD

**Issue by Vad1mo** [h0tbird/docker-portus#15]
you could simplify your image more. Environmental variables are not needed as Portus support them out of the box. 

http://port.us.org/docs/Configuring-Portus.html#override-specific-configuration-options

**Comment by h0tbird** [comment]
Have you tried it? Does it really work? I remember the last time I checked Portus wasn't natively honouring the envars. I think they were using some interpolation method to render the config before starting the process (as I do).

I am willing to change this if the situation has changed.

**Comment by Vad1mo** [comment]
You are right, they only support a few options.

Maybe this would be an elegant alternative for this image or even better for portus. 

https://github.com/progrium/entrykit
https://github.com/kreuzwerker/envplate
https://github.com/markround/tiller
