### ISSUE TITLE
missing portus user

### ISSUE THREAD

**Issue by Gladmir** [h0tbird/docker-portus#7]
Hi,

Portus' database needs to be provisioned I presume since it's complaining about the missing 'portus' user. 

Also, when it tries to access to underlying registry, it cannot get the image hashes (401 authorization error).

I think the setup_databases() from compose-setup.sh needs to be integrated here also.
```
setup_database() {
  set +e

  TIMEOUT=90
  COUNT=0
  RETRY=1

  while [ $RETRY -ne 0 ]; do
    if [ "$COUNT" -ge "$TIMEOUT" ]; then
      printf " [FAIL]\n"
      echo "Timeout reached, exiting with error"
      exit 1
    fi
    echo "Waiting for mariadb to be ready in 5 seconds"
    sleep 5
    COUNT=$((COUNT+5))

    printf "Portus: configuring database..."
    docker-compose run --rm web rake db:migrate:reset > /dev/null
    docker-compose run --rm web rake db:seed > /dev/null

    RETRY=$?
    if [ $RETRY -ne 0 ]; then
        printf " failed, will retry\n"
    fi
  done
  printf " [SUCCESS]\n"
  set -e
}
```

**Comment by h0tbird** [comment]
You are right about the missing portus user. To workaround this you must create the user the very first time you access `Portus` (when you are prompted for a user and password). Please read the README as I have already documented this.

I setup the database [here](https://github.com/h0tbird/docker-portus/blob/9766ba566391ff646ed1e39cc85167e0f25112f6/rootfs/init#L77) perhaps I am missing the `rake db:seed` I am not sure about this.

**Comment by Gladmir** [comment]
Ah, ok;

"Browse to https://127.0.0.1 and setup the portus user with the same password provided in the environment variable PORTUS_PORTUS_PASSWORD. Do not fill the New Registry form until you have actually started the registry in step 4."

My bad, I completely missed that.

**Comment by NickHu** [comment]
According to
https://github.com/SUSE/Portus/blob/2fcfedf0619da3dde0533293b35c29619bac0cac/compose-setup.sh#L46-L48
the correct way to setup the database is to do
```bash
rake db:migrate:reset
rake db:seed
```
and indeed in my own tests this has removed the need to manually setup the `portus` user.

**Comment by h0tbird** [comment]
Great, I'll give it a try.
